--DROP SEQUENCE SEQ_BH_ENVIROMENT  
CREATE SEQUENCE SEQ_BH_ENVIROMENT  
    START WITH 1  
    INCREMENT BY 1 ;  

--DROP TABLE BH_TYPE_ENVIROMENT
CREATE TABLE BH_TYPE_ENVIROMENT(
TYE_NCODE INT PRIMARY KEY,
TYE_CNAME VARCHAR(12),
TYE_CDESCRIPTION VARCHAR(20)
)

--DROP TABLE BH_ENVIROMENT
CREATE TABLE BH_ENVIROMENT(
ENV_NCODE INT NOT NULL ,
ENV_CNAME VARCHAR(20),
ENV_CBRANCHNAME VARCHAR(15),
ENV_CAPPLICATIONDB VARCHAR(50),
ENV_CSECURITYDB VARCHAR(50),
ENV_CTRANSPORTDB VARCHAR(50),
TYE_NCODE INT,
PRIMARY KEY (ENV_NCODE),
CONSTRAINT FK_TYPE_ENVIROMENT FOREIGN KEY (TYE_NCODE)
        REFERENCES BH_TYPE_ENVIROMENT(TYE_NCODE)
)

--

INSERT INTO BH_TYPE_ENVIROMENT VALUES(1,'D','Desarrollo')
INSERT INTO BH_TYPE_ENVIROMENT VALUES(2,'R','Release')
--

INSERT INTO BH_ENVIROMENT VALUES (NEXT VALUE FOR SEQ_BH_ENVIROMENT,'Control de Cambios','BH_RELEASE_CC','BeyondHealth_Changes','BeyondHealth_SecurityColpatria_CC','BeyondHealth_Transport_CC',2);
INSERT INTO BH_ENVIROMENT VALUES (NEXT VALUE FOR SEQ_BH_ENVIROMENT,'Sonda QA','BH_RELEASE_QA','BHColpQA_Application','BHColpQA_Security','BHColpQA_TransportServices',2);
INSERT INTO BH_ENVIROMENT VALUES (NEXT VALUE FOR SEQ_BH_ENVIROMENT,'Sonda UAT','BH_RELEASE_UAT','BHColpUAT_Application','BHColpUAT_Security','BHColpUAT_TransportServices',2);
